---
# handlers file for install_wordpress yy

- name: Restart apache
  ansible.builtin.shell: |
    if [ "{{ ansible_os_family }}" = "Debian" ]; then
      service apache2 restart
    else
      pkill httpd || true
      /usr/sbin/httpd -DFOREGROUND &
    fi
  become: true
  changed_when: true

- name: Reload apache
  ansible.builtin.shell: |
    if [ "{{ ansible_os_family }}" = "Debian" ]; then
      service apache2 reload
    else
      pkill httpd || true
      /usr/sbin/httpd -DFOREGROUND &
    fi
  become: true
  changed_when: true

- name: Restart mariadb
  ansible.builtin.shell: |
    pkill mysqld || true
    sleep 2
    mysqld_safe --datadir=/var/lib/mysql --user=mysql &
    sleep 5
  become: true
  changed_when: true

- name: Start mariadb
  ansible.builtin.shell: |
    mysqld_safe --datadir=/var/lib/mysql --user=mysql &
    sleep 5
  become: true
  changed_when: true

- name: Start apache
  ansible.builtin.shell: |
    if [ "{{ ansible_os_family }}" = "Debian" ]; then
      service apache2 start
    else
      /usr/sbin/httpd -DFOREGROUND &
    fi
  become: true
  changed_when: true
